const normalizePath = (value) => {
  if (typeof value !== 'string' || !value.trim()) return ''
  try {
    const baseUrl = typeof window === 'undefined' ? 'http://localhost' : window.location.origin
    return new URL(value, baseUrl).pathname
  } catch {
    return value.trim()
  }
}

const OPTIMIZABLE_IMAGE = /\.(?:jpe?g|png)(?=([?#]|$))/i

/**
 * Existing repository media has a WebP companion generated by
 * scripts/optimize-images.ps1. Uploaded media can still fall back to its
 * original URL when a companion has not been generated yet.
 */
export const optimizedImageUrl = (imageUrl) => {
  if (typeof imageUrl !== 'string' || !imageUrl.trim()) return ''
  const value = imageUrl.trim()
  if (!OPTIMIZABLE_IMAGE.test(value) || /^(?:data|blob):/i.test(value)) return value
  return value.replace(OPTIMIZABLE_IMAGE, '.webp')
}

export const isRenderableRecipeImage = (imageUrl) => {
  return Boolean(normalizePath(imageUrl))
}
