CREATE TABLE IF NOT EXISTS agent_action (
    id BIGINT NOT NULL AUTO_INCREMENT,
    confirmation_token VARCHAR(64) NULL,
    request_key CHAR(64) NOT NULL,
    user_id INT NOT NULL,
    tool_name VARCHAR(64) NOT NULL,
    arguments_json TEXT NULL,
    summary VARCHAR(500) NOT NULL,
    requires_confirmation TINYINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    result_message VARCHAR(1000) NULL,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_action_token (confirmation_token),
    KEY idx_agent_action_user_created (user_id, created_at),
    KEY idx_agent_action_pending (user_id, request_key, status, expires_at)
);

CREATE TABLE IF NOT EXISTS agent_run (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id CHAR(32) NOT NULL,
    user_id INT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    model VARCHAR(128) NOT NULL,
    input_modality VARCHAR(20) NOT NULL,
    status VARCHAR(32) NOT NULL,
    latency_ms BIGINT NOT NULL DEFAULT 0,
    llm_calls INT NOT NULL DEFAULT 0,
    tool_calls INT NOT NULL DEFAULT 0,
    successful_tools INT NOT NULL DEFAULT 0,
    failed_tools INT NOT NULL DEFAULT 0,
    confirmation_required TINYINT NOT NULL DEFAULT 0,
    prompt_version VARCHAR(64) NULL,
    prompt_tokens INT NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    error_type VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_run_run_id (run_id),
    KEY idx_agent_run_user_created (user_id, created_at),
    KEY idx_agent_run_created_status (created_at, status)
);
